name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  simple_animations: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  percent_indicator: ^4.2.5
  image_picker: ^1.2.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flex_color_picker: ^3.7.1
  flutter_colorpicker: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  fl_chart: ^1.1.1
  rive: ^0.13.4
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  json_annotation: ^4.9.0
  syncfusion_flutter_gauges: ^31.2.2
  path: ^1.9.1
  smooth_page_indicator: ^1.2.1
  freezed_annotation: ^2.4.1
  table_calendar: ^3.2.0
  http: ^1.5.0
  flutter_html: ^3.0.0
  url_strategy: ^0.3.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  timeline_tile: ^2.0.0
  flutter_native_splash: ^2.4.7
  permission_handler: ^12.0.1
  firebase_core: ^4.2.1
  firebase_ai: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/acuario/
    - assets/luna_png/
    - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon" # Can be true or a path to the icon image
  ios: true
  image_path: "assets/icons/icon.png"
  web: 
    generate: true
    image_path: "assets/icons/icon.png"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/luna_png/luna_splash_w.png
  image_dark: assets/luna_png/luna_splash_b.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    image: assets/luna_png/luna_splash_w.png
    image_dark: assets/luna_png/luna_splash_b.png
